//TYPES, Objeto con las acciones
export const TYPES ={
    AUMENTAR:'AUMENTAR',
    DISMINUIR:'DISMINUIR',
    AGREGAR_CARRO:'AGREGAR_CARRO',
    QUITAR_CARRO:'QUITAR_CARRO',
    LIMPIAR_CARRO:'LIMPIAR_CARRO',
    PAGAR_CARRO:'PAGAR_CARRO',
};

